import "./globals.css";
import { Navbar } from "@/components/layout";
import { Providers } from "@/providers/Providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<head>
				<link
					crossOrigin="anonymous"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
					integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
					referrerPolicy="no-referrer"
					rel="stylesheet"
				/>
			</head>
			<body className="bg-gradient-to-r from-cyan-500 to-blue-500 flex flex-col gap-4">
				<Providers>
					<Navbar />
					<main className="p-5">{children}</main>
				</Providers>
			</body>
		</html>
	);
}
