import "./globals.css";
import { Providers } from "@/providers/Providers";
import type { Metadata } from "next";

export const metadata: Metadata = {
	description: "Generated by create next app",
	title: "Create Next App",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
